export const LOCATION_LOADING = "LOCATION_LOADING";
export const LOCATION_ADD_SUCCESS = "LOCATION_ADD_SUCCESS";
export const LOCATION_LIST_SUCCESS = "LOCATION_LIST_SUCCESS";
export const LOCATION_DELETE_SUCCESS = "LOCATION_DELETE_SUCCESS";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const LOCATION_SINGLE_SUCCESS = "LOCATION_SINGLE_SUCCESS";
export const LOCATION_UPDATE_SUCCESS = "LOCATION_UPDATE_SUCCESS";
